apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlops-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mlops-chart
      app.kubernetes.io/instance: mlops-app
  endpoints:
  - port: metrics
    path: /metrics
    targetPort: 8001