apiVersion: apps/v1
kind: Deployment₩
metadata:
  name: {{ include "mlops-chart.fullname" . }}
  labels:
    {{- include "mlops-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mlops-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlops-chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mlops-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP