{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mlops-chart.fullname" . }}
  labels:
    {{- include "mlops-chart.labels" . | nindent 4}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end}}
spec:
  ingressClassName: alb
  rules:
    {{- range .Values.ingress.hosts}}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mlops-chart.fullname" $ }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end}}
       