apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops-chart.fullname" . }}
  labels:
    {{- include "mlops-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: metrics
  selector:
    {{- include "mlops-chart.selectorLabels" . | nindent 4 }}
