# Default values for mlops-chart.

# Container image settings
image:
  repository: myusername/mlops-project  # Replace with your Docker Hub username
  pullPolicy: IfNotPresent
  tag: "latest"

# Service settings for exposing the app
service:
  type: LoadBalancer
  port: 80

# ServiceAccount settings
serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

# Ingress settings
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
  hosts:
    - host: "*"
      paths:
        - path: /
          pathType: Prefix